[[plugins]]
  package = "@netlify/plugin-lighthouse"
 
  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.6
    accessibility = 0.8
    best-practices = 0.9
    seo = 0.9
    # pwa = 0.9